"""
continuum_cross_stream_reconcile.py
Cross-Stream Recursive Reconciliation + Dashboard Export
Version: 1.2

Purpose:
- Read reports/live_event_state.json generated by SEAM
- Preserve SEAM event identity
- Preserve live/raw vs delayed/curated source lineage
- Export dashboard-compatible data/latest.json

Dashboard schema emitted:
- region
- hypothesis
- realization_probability
- persistence
- observation_count
- lat
- lon
- state
- trajectory
- sources
- evidence
- contradictions
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parent

INPUT_PATH = ROOT / "reports" / "live_event_state.json"
REPORT_OUTPUT = ROOT / "reports" / "cross_stream_manifolds_current.json"
DASHBOARD_OUTPUT = ROOT / "data" / "latest.json"

DISTANCE_THRESHOLD_MILES = 0.5
TIME_THRESHOLD_SECONDS = 300


def load_payload():
    if not INPUT_PATH.exists():
        print(f"[RECONCILE] Missing input: {INPUT_PATH}")
        return {}

    try:
        with open(INPUT_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as exc:
        print(f"[RECONCILE] Failed loading payload: {exc}")
        return {}


def classify_sources(sources):
    live = []
    delayed = []

    for source in sources or []:
        normalized = str(source).replace("\\", "/").lower()

        if "/raw/" in normalized:
            live.append(source)
        elif "/curated/" in normalized:
            delayed.append(source)

    return live, delayed


def region_label(event):
    regime = str(event.get("primary_regime", "event")).upper()
    lat = event.get("latitude", 0.0)
    lon = event.get("longitude", 0.0)

    try:
        return f"{regime} {float(lat):.2f}, {float(lon):.2f}"
    except Exception:
        return regime


def build_hypothesis(event, live_count, delayed_count, convergence):
    regime = str(event.get("primary_regime", "event")).upper()
    verification = event.get("verification_state", "UNVERIFIED")
    lead_time = int(event.get("lead_time_seconds", 0))
    confidence = float(event.get("forecast_confidence", 0.0))

    return (
        f"{regime} target {verification.lower()} | "
        f"confidence {confidence:.2f} | "
        f"lead {lead_time}s | "
        f"live {live_count} / delayed {delayed_count} | "
        f"convergence {convergence:.2f}"
    )


def reconcile(events):
    manifolds = []
    dashboard_events = []

    for index, event in enumerate(events):
        lat = event.get("latitude")
        lon = event.get("longitude")

        if lat is None or lon is None:
            continue

        live_sources, delayed_sources = classify_sources(event.get("sources", []))

        live_count = len(live_sources)
        delayed_count = len(delayed_sources)
        total_sources = max(1, live_count + delayed_count)

        confidence = float(event.get("forecast_confidence", event.get("seam_phi", 0.0)) or 0.0)
        convergence = min(1.0, total_sources / 10.0)

        state = event.get("lock_state", "MONITOR")
        verification = event.get("verification_state", "UNVERIFIED")

        trajectory = (
            "confirmed"
            if verification == "CONFIRMED"
            else "predicted"
            if verification == "PREDICTED_ONLY"
            else "tracking"
        )

        event_id = event.get("event_id", f"EVT-{index:06d}")

        manifold = {
            "manifold_id": f"MANI-{index:05d}",
            "event_id": event_id,
            "timestamp_utc": datetime.now(timezone.utc).isoformat(),
            "primary_regime": event.get("primary_regime", "unknown"),
            "lock_state": state,
            "verification_state": verification,
            "latitude": lat,
            "longitude": lon,
            "forecast_confidence": confidence,
            "observation_count": event.get("observation_count", 0),
            "live_source_count": live_count,
            "delayed_source_count": delayed_count,
            "source_convergence": round(convergence, 3),
            "lead_time_seconds": int(event.get("lead_time_seconds", 0)),
            "trajectory_state": trajectory
        }

        manifolds.append(manifold)

        dashboard_events.append({
            "event_id": event_id,
            "region": region_label(event),
            "hypothesis": build_hypothesis(event, live_count, delayed_count, convergence),
            "realization_probability": confidence,
            "persistence": convergence,
            "observation_count": event.get("observation_count", 0),
            "lat": lat,
            "lon": lon,
            "state": state,
            "trajectory": trajectory,
            "primary_regime": event.get("primary_regime", "unknown"),
            "verification_state": verification,
            "lead_time_seconds": int(event.get("lead_time_seconds", 0)),
            "live_source_count": live_count,
            "delayed_source_count": delayed_count,
            "source_convergence": round(convergence, 3),
            "sources": event.get("sources", []),
            "evidence": [
                f"verification_{verification.lower()}",
                f"live_sources_{live_count}",
                f"delayed_sources_{delayed_count}",
                f"lead_time_{int(event.get('lead_time_seconds', 0))}s"
            ],
            "contradictions": []
        })

    return manifolds, dashboard_events


def export_manifolds(manifolds):
    REPORT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    payload = {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "distance_threshold_miles": DISTANCE_THRESHOLD_MILES,
        "time_threshold_seconds": TIME_THRESHOLD_SECONDS,
        "manifold_count": len(manifolds),
        "manifolds": manifolds
    }

    with open(REPORT_OUTPUT, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def export_dashboard(events):
    DASHBOARD_OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    payload = {
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "event_count": len(events),
        "active_events": events
    }

    with open(DASHBOARD_OUTPUT, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def main():
    payload = load_payload()
    events = payload.get("events", [])

    print()
    print("=== SEAM CROSS-STREAM RECONCILIATION v1.2 ===")
    print()
    print(f"Input events: {len(events)}")

    manifolds, dashboard_events = reconcile(events)

    export_manifolds(manifolds)
    export_dashboard(dashboard_events)

    print(f"Manifolds: {len(manifolds)}")
    print(f"Dashboard events: {len(dashboard_events)}")
    print(f"Reports: {REPORT_OUTPUT}")
    print(f"Dashboard: {DASHBOARD_OUTPUT}")
    print()


if __name__ == "__main__":
    main()
